quarkus.http.port=${QUARKUS_HTTP_PORT:9292}
quarkus.http.cors=true
quarkus.http.cors.methods=*
quarkus.http.cors.origins=*
brix.dev.web.root=../target/gwt/launcherDir/app
brix.application.root=./
brix.dev.application.root=app
brix.api.url=/api/
quarkus.security.providers=BC
quarkus.log.level=ERROR
quarkus.log.console.level=ERROR
