quarkus.http.port=${QUARKUS_HTTP_PORT:8090}
quarkus.http.cors=true
quarkus.http.cors.methods=*
quarkus.http.cors.origins=*
brix.dev.web.root=../target/gwt/launcherDir
brix.application.root=
%remote.brix.application.root=/domino-ui/demo/v2
brix.dev.application.root=${BRIX_DEV_APPLICATION_ROOT:app}
brix.api.url=/api/
%remote.brix.api.url=/domino-ui/demo/v2/api/
